# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDU-xTkYOFlSqlneS3ySyfMoOS3lu6RB
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Ustawienie tytułu aplikacji Streamlit
st.title("🎅 Święty Mikołaj w Streamlit (Rysunek Matplotlib)")

# Utworzenie figury i osi Matplotlib
fig, ax = plt.subplots(figsize=(6, 8))
ax.set_xlim(0, 10)
ax.set_ylim(0, 12)
ax.set_aspect('equal', adjustable='box')
ax.axis('off') # Ukrycie osi

# --- 1. Ciało Mikołaja (Czerwony Strój) ---
# Tors (prostokąt)
# Ulepszenie: Lepszy kolor czerwony
ax.add_patch(patches.Rectangle((3.5, 3.5), 3, 4, color='#DC143C', alpha=0.9))

# Pas (czarny prostokąt)
ax.add_patch(patches.Rectangle((3.5, 5.0), 3, 0.5, color='black'))

# Klamra pasa (żółty/złoty kwadrat)
ax.add_patch(patches.Rectangle((4.7, 5.0), 0.6, 0.5, color='#FFD700'))

# --- 2. Głowa i Broda ---
# Głowa (koło)
ax.add_patch(patches.Circle((5, 8.5), 1, color='#F0CC9C')) # Podniesienie głowy

# Broda (owal/koło pod głową)
# Ulepszenie: Lepszy kształt brody
ax.add_patch(patches.Ellipse((5, 7.5), 3, 2, color='white', zorder=2))
ax.add_patch(patches.Circle((5, 7.5), 0.5, color='white', zorder=3)) # Dodatkowa biała "kępka" na nos i policzki

# Oczy (małe czarne kropki)
ax.add_patch(patches.Circle((4.5, 8.7), 0.1, color='black'))
ax.add_patch(patches.Circle((5.5, 8.7), 0.1, color='black'))

# --- 3. Czapka ---
# Czerwony stożek czapki (trójkąt)
# Ulepszenie: Kształt czapki pochylony
ax.add_patch(patches.Polygon([[4, 9.5], [6.2, 9.5], [5.8, 11.5]], closed=True, color='red'))

# Biały pasek na dole czapki (prostokąt)
ax.add_patch(patches.Rectangle((3.8, 9.3), 2.6, 0.5, color='white'))

# Biały pompon na czubku czapki (koło)
ax.add_patch(patches.Circle((5.8, 11.5), 0.45, color='white'))

# --- 4. Ręce i Buty (Dodane dla lepszego wyglądu) ---
# Buty (dwa czarne prostokąty)
ax.add_patch(patches.Rectangle((4.0, 3.0), 0.7, 0.5, color='black'))
ax.add_patch(patches.Rectangle((5.3, 3.0), 0.7, 0.5, color='black'))

# Ręce (dwa czerwone koła)
ax.add_patch(patches.Circle((3.2, 6.5), 0.5, color='red')) # Lewa ręka
ax.add_patch(patches.Circle((6.8, 6.5), 0.5, color='red')) # Prawa ręka

# --- 5. Prezenty (Worek) ---
# Worek na prezenty (większy, zielony prostokąt, z tyłu)
ax.add_patch(patches.Rectangle((6.0, 3.5), 2.5, 3.5, color='#006400', alpha=0.9, zorder=1))

# Wystające prezenty (zmienione kolory i rozmieszczenie)
ax.add_patch(patches.Rectangle((6.3, 7.0), 0.6, 0.6, color='#FF4500')) # Pomarańczowy
ax.add_patch(patches.Rectangle((7.0, 7.2), 0.7, 0.7, color='#1E90FF')) # Niebieski
ax.add_patch(patches.Rectangle((7.8, 6.8), 0.5, 0.5, color='#DAA520')) # Złoty
ax.add_patch(patches.Rectangle((6.8, 7.8), 0.5, 0.5, color='#3CB371')) # Ciemnozielony

# Tekst świąteczny
ax.text(5, 1.5, "Ho Ho Ho!", fontsize=20, ha='center', color='#DC143C', fontweight='bold')
ax.text(5, 0.8, "Wesołych Świąt!", fontsize=14, ha='center', color='black')

# Wyświetlenie obrazka w Streamlit
st.pyplot(fig)